trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Install Node.js and npm
    sudo apt-get update
    sudo apt-get install -y nodejs npm
    nodejs -v
    npm -v
  displayName: 'Install Node.js and npm'

- script: |
    echo Install Cypress
    npm install cypress
  displayName: 'Install Cypress'

- script: |
    echo Run Cypress tests
    npx cypress run
  displayName: 'Run Cypress tests'
